### ISSUE TITLE
data array for AWATTAR not starting at midnight

### ISSUE THREAD

**Issue by mutzl** [mampfes/ha_epex_spot#10]
When using AWATTAR (at or de) as provider, the data array in the attributes of the sensor start at 00:00 UTC.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/2855185/214108479-10eb96a2-3322-4bd1-aac3-c71ce58fe71a.png">

I assume, the intention is providing the whole range of 24 (or 48 if already available) hours.
So the query should start at midnight _local time_. 
Otherwise the first slot is missing. Or even two slots during daylight saving time.

**Comment by mampfes** [comment]
No, the idea is not to get exactly 24 or 48h. The idea is to get the values for today and as much in the future as available - which is typically between 8h (before ~14:00) and 32h (after ~14:00) (if I remember correctly).
The start time is actually 00:00 UTC time, so you get 1h (or 2h during CEST) more (not less) than if you start with local German time.
UTC time is the common format for time data, therefore more suitable for any kind of further processing.

**Comment by mutzl** [comment]
Yes - I know, that there are between 10h and 34h of data slots into the future, depending on the current time.

Anyway - from a UX point of view, it feels weird to me, if the first slot in a daily based chart is missing. 
See your own sample with 47 bars in the chart.
![apexchart](https://github.com/mampfes/ha_epex_spot/raw/main/images/apexcharts.png)


But fine for me, if you have a different opinion on that. After all, it's your integration and I just wanted to provide feedback. (And I just wrote my own implementation using NetDaemon anyway.)

**Comment by mampfes** [comment]
Ah, now I understand your problem :-) Sorry that I didn't get it yesterday. Obviously I was pretty confused yesterday because most of the things I wrote yesterday are simply wrong.

I will check the issue.
