### ISSUE TITLE
aWATTar formula error

### ISSUE THREAD

**Issue by 32u-nd** [mampfes/ha_epex_spot#100]
Good afternoon,
it seems that your formula is not correctly applicable for aWATTar. I also contacted the aWATTar service hotline to get a clarification. The fix offset/absolute surcharge (net usage, taxes, fees, etc.) is already gross price including VAT. The same is true for the basic monthly fee (not included in your formula). The EPEX is net price, so we need to apply the percentage surcharge *and* VAT to it:
> Net Price = ((Market Price * 1.03) + 12ct) * 1.19

from the documentation should be
> Net Price = ((Market Price * 1.03 * 1.19) + 12ct)

Example from aWATTar page: 2024-01-23, slot 1700h-1800h
> 8.16 ct/kWh net without any VAT == 9.71 ct/kWh gross incl. 19% VAT
> 17.34 ct/kWh fix offset (for my location)
> aWATTar grid price incl. VAT = 17.34 ct/kWh + 8.16 ct/kWh * 1.2257 = 17.34 ct/kWh + 9.71 ct/kWh * 1.03 = 27.34 ct/kWh

So, combining the aWATTar 3% surcharge with 19% VAT is a 22.57% surcharge in total. I would also like to propose a small adjustment in the documentation to mitigate confusions with the terms "net" and "market":
> GrossGridPrice == EPEXNetPrice * PercentageSurcharge * VAT + GrossAbsoluteSurcharge

**Comment by mampfes** [comment]
Thanks for the detailed description.

The formula is not Awattar specific, but used for all suppliers. And as it is already used by a lot of people, I can't simple change it without breaking a lot of peoples configuration. 

The formula expects absolute surcharge excluding VAT. So if Awattar is already including VAT in the absolute surcharge, you just have to remove it again to get the right values:
`17.34 / 1.19 = 14.57 ct/kWh` absolute surcharge.

Regarding the documentation: I found a lot of different, especially contradictive, definitions on the internet. As I am no financial  expert I can not assess which one is right. But what I can do is to add more description to make things clearer.

**Comment by Celphor** [comment]
It's even worse in Austria. You also have an additional surcharge (1.5 cent) with newer contracts. Luckily I have an old contract without the surcharge ;-) VAT is added on top off all (net price * 1.03 + 1.5 Cent) * 1.2

![image](https://github.com/mampfes/ha_epex_spot/assets/22246844/a68c998f-f916-4277-a5fc-64f440b56235)

**Comment by 32u-nd** [comment]
> Thanks for the detailed description.
> 
> The formula is not Awattar specific, but used for all suppliers. And as it is already used by a lot of people, I can't simple change it without breaking a lot of peoples configuration.
> 
> The formula expects absolute surcharge excluding VAT. So if Awattar is already including VAT in the absolute surcharge, you just have to remove it again to get the right values: `17.34 / 1.19 = 14.57 ct/kWh` absolute surcharge.
> 
> Regarding the documentation: I found a lot of different, especially contradictive, definitions on the internet. As I am no financial expert I can not assess which one is right. But what I can do is to add more description to make things clearer.

Yes, this is what I did as well for me; thanks for your reply.

**Comment by 32u-nd** [comment]
see comments above; you need to tweak the constants a bit to suite for your needs :)

**Comment by nin9s** [comment]
> It's even worse in Austria. You also have an additional surcharge (1.5 cent) with newer contracts. Luckily I have an old contract without the surcharge ;-) VAT is added on top off all (net price * 1.03 + 1.5 Cent) * 1.2 So one model doesn't fit all
> 
> To get the "all in" price there must also be added area dependent network costs per kwh
> 
> ![image](https://github.com/mampfes/ha_epex_spot/assets/22246844/a68c998f-f916-4277-a5fc-64f440b56235)

may I ask you how what you did to include everything in the calculation for Awattar Austria?
