### ISSUE TITLE
smartenergy.at as datasource not working

### ISSUE THREAD

**Issue by ar-ml** [mampfes/ha_epex_spot#102]
see screenshot below.

Awattar ist working though!

![grafik](https://github.com/mampfes/ha_epex_spot/assets/28296008/345dca87-2bf5-40c4-8dc5-4daad6a34bd8)

**Comment by mampfes** [comment]
Could you please check if there are errors in the log? I can't reproduce this issue so far.

**Comment by feutl** [comment]
I am having the same problem since yesterday after updating to the latest version.
What information should I am looking for, as for me it looks a little different

![image](https://github.com/mampfes/ha_epex_spot/assets/8522012/00b99fd5-74dc-49f8-86f6-4bebf1ebc1a6)

The second Spot Service via Awattar works without problems.

**Comment by mampfes** [comment]
The smartENERGY API is currently defect: It doesn't return valid values. So there is nothing we can do on our side. Please reach out to smartENERGY.

https://apis.smartenergy.at/market/v1/price --> `{"tariff":"EPEXSPOTAT","unit":"ct/kWh","interval":15,"data":[]}`

**Comment by feutl** [comment]
ah, ok, this makes sense, lets see what they gonna do to fix it. I will reach out to them, as a customer :)

**Comment by ar-ml** [comment]
they recently changed their website, probably killed the API...  I will write them also as customer.

**Comment by ar-ml** [comment]
They just wrote me back:
Die API sollte mit morgen wieder verlässlich funktionieren.

**Comment by markus-gitdev** [comment]
Had the same issue, but it works again for me. It seems they were able to fix their issue.

**Comment by BjoernRoethig** [comment]
API seems to work again - showing correct values when they get triggered directly. But EPEX HA integration somehow shows prices more than doubled.

**Comment by BjoernRoethig** [comment]
API showing different values than EPEX integration
![image](https://github.com/mampfes/ha_epex_spot/assets/104513066/20525ee0-6d78-4827-8f69-046649353ca7)

They must pull data from different sources (https://apis.smartenergy.at/market/v1/price)
![image](https://github.com/mampfes/ha_epex_spot/assets/104513066/5af75933-1971-43c6-9b3b-559ecae6f328)

Net Price in HA shows right now 22,73ct/kWh - API shows 8.358 ct/kWh. 

Also when I compare Awattar - same issue. Market prices do not match. I installed a fresh extension in HA - no change. Idea? Everything was working until two days ago...

**Comment by mampfes** [comment]
@BjoernRoethig SmartEnergy reports values including VAT, all other service providers report values excluding VAT. Therefore, VAT will be removed for SmartEnergy. Then the configured taxes will be applied. Do you have different configurations for SmartEnergy and Awattar?

In my setup, SmartEnergy and Awattar report equal values.

**Comment by BjoernRoethig** [comment]
@mampfes Thank you for your input. I know - both sensors where working fine for months now... I did not change anything - three days ago - suddenly no data at all for about 48 hrs... also on smartenergy homepage - no data. Then data came back online... with complete abnormal prices. 
The shown "Net Price" does not match at all the remaining prices... I know - setup can be influenced with surcharge an tax... 
well - than some other update is influencing the calculation. I let you know when I find out.

**Comment by BjoernRoethig** [comment]
After a long try and error run - I found the issue. The config of the file updated to the "original" values after I got a new version. 
I did not think about that - as I have set the values during initial setup - and all where correct. That an update will change the config - did not cross my mind. 
Anyway - in general all are working - just the smartenergy API seems not very stable.
