### ISSUE TITLE
Future price values?

### ISSUE THREAD

**Issue by ar-ml** [mampfes/ha_epex_spot#103]
Just a question:
Does your integration also provide future market price values for the next day?

https://www.smartenergy.at/ wrote on their [website](https://www.smartenergy.at/smartcontrol#/smartcontrol#c556):
" Wir verraten dir bereits heute die stündlichen Preise für den nächsten Tag. Somit kannst du einschalten, wann immer der Strom am günstigsten für dich ist."
("We will already reveal to you the hourly prices for the next day today. This way, you can turn on whenever the electricity is cheapest for you.")

So I assume it would be helpful to get those future values also?

Without future values, how could your addon https://github.com/mampfes/ha_epex_spot_sensor predict the best time window for switching the device on?

**Comment by mampfes** [comment]
Yes, that is the idea of this integration.

Prices for the next day will be published by EPEX Spot at around 2pm and will be fetched by this integration from one of the supported service providers.

**Comment by ar-ml** [comment]
Thx for your answer.

What I don't understand is, why the chart for sensor.epex_spot_data_price does not display any values for the future:

![grafik](https://github.com/mampfes/ha_epex_spot/assets/28296008/2fa1d9b6-8545-4639-9059-c146d62c49e5)

**Comment by mampfes** [comment]
This is the HA history which can only show historical data. The future values are available as attributes of the price sensor. If you want to have a chart you can use ApexCharts as described in the documentation.
