### ISSUE TITLE
new sensor

### ISSUE THREAD

**Issue by pabe40** [mampfes/ha_epex_spot#104]
Hi mampfes,
would you considder creating a similar sensor to "Net Market Price Sensor".
This sensor is used for import net prices.
I would like to have natively a "Net Market export Price Sensor"
This is in most situation having other parameters for calculation the net export price than the net import price.
Net import Price = Market Price + import Surcharges + Tax
versus
Net export Price = Market Price + export Surcharges

**Comment by mampfes** [comment]
Sorry, I don't fully understand your request. Do you need an import and an export sensor at the same time?
What does import and export mean?
