### ISSUE TITLE
Awattar "last day" after update

### ISSUE THREAD

**Issue by Swimmer71** [mampfes/ha_epex_spot#105]
Hi,
first of all thanks for the wonderful integration, I love it. After the update 2 days ago, I see now for the Awattar (at) sensor the actual day, and after 14pm the data for tomorrow (so far so good). BUT now, additionally I always see the last day also. Is this what you want? I have to change my diagrams now because I then need the slices 25-48 for today and 49-72 for tomorrow (because slice 1-24 is now yesterday).
I also deleted awattar sensor and set it up newly, the same situation.

e.g: today is 4.2.2024 10am, and I see all data from 3.2.2024 and todays data. After 14pm I will see also tomorrows data, but yesterdays data won't dissapear.

**Comment by mampfes** [comment]
Hi, this is by intention: Yesterdays data is needed for [EPEX Spot Sensor](https://github.com/mampfes/ha_epex_spot_sensor).
Please adjust your diagrams accordingly.

**Comment by Swimmer71** [comment]
Just for confirming, this is new since last update, right?
----------------------------------------

04.02.2024 11:51:47 Steffen Zimmermann ***@***.***>:
