### ISSUE TITLE
Price in ct/kWh seems to be a problem

### ISSUE THREAD

**Issue by angeeinstein** [mampfes/ha_epex_spot#107]
Having the price in ct seems to be a problem for Home Assistant. The calculation for the daily electricity cost is way too high when I select Net price as an entity for cost calculation. How does it work for other people?

**Comment by Mightyjust** [comment]
Same problem for me - it works as intended  when using spot data price. Would love to know how to use the net price sensor too.

**Comment by mampfes** [comment]
The temporary solution is to add a template sensor which converts ct/kWh from the net-price sensor into EUR/kWh.
The long-term solution is more complicated: Either I have to make the unit-of-measure configurable or the HA unit-of-measure system can be enhanced to convert between different energy prices.

**Comment by knorp** [comment]
Same issue here, I'll check out the template. Maybe just simply duplicating the sensor with a different unit would be an option as a quick fix without unit configuration?

**Comment by mampfes** [comment]
Example:

`{{ states('sensor.epex_spot_data_net_price') | float / 100  }}`

![image](https://github.com/mampfes/ha_epex_spot/assets/375950/15c39493-3fdd-48d0-8985-71da3359ba05)

**Comment by Mightyjust** [comment]
thank you, both methods work perfectly!

**Comment by gismo2004** [comment]
@mampfes Was there an action/issue/defect/feature on Home Assistant side in regard to unit conversion, or will that be the future solution to create this template sensor?

**Comment by mampfes** [comment]
@gismo2004 No, not yet.
