### ISSUE TITLE
smartENERGY (Austria) Net Price Calculation incorrect

### ISSUE THREAD

**Issue by AkshayRao27** [mampfes/ha_epex_spot#108]
There’s a mismatch between the current price shown on the smartENERGY website and what the sensor calculates. 

As of time of writing, the electricity price is ¢8.55 according to the website, and my sensor shows ¢8.842 (¢1.44 surcharge and 20% tax).

The smartENERGY API entry for right now says ¢7.114 which is exactly ¢1.44 short of what their website says.

No matter how I configure the integration, I cannot seem to reach this value. If I include both tax and surcharge, the sensor over reports (current config). If I include just the surcharge but 0% tax, then it under reports. 

According to smartENERGY, the prices reported by the API already include 20% tax, so the sensor needs to simply add a static ¢1.44 (the current surcharge) to every price value from the API.

**Comment by mampfes** [comment]
You have to configure your taxes and surcharges as described in the Net Price Sensor chapter: https://github.com/mampfes/ha_epex_spot?tab=readme-ov-file#1-net-market-price-sensor

![image](https://github.com/mampfes/ha_epex_spot/assets/375950/0a7fe2f2-5a92-4d78-9e6c-1f694760034d)

**Comment by angeeinstein** [comment]
> According to smartENERGY, the prices reported by the API already include 20% tax

That is wrong, even though they say it on their website. The provided price from smartENERGY is without tax. It's the same as on the EPEX Spot website. You have to add a surcharge of 1,2ct and then 20% tax. That gives you the 1,44ct (1,2×1,2) surcharge that you really pay to smartENERGY.

**Comment by AkshayRao27** [comment]
Okay, that fixes it. I guess the ticket can be closed - might be a good idea to mention this in the documentation somewhere 😉

**Comment by AkshayRao27** [comment]
Okay, that fixes it. I guess the ticket can be closed - might be a good idea to mention this in the documentation somewhere 😉

**Comment by angeeinstein** [comment]
I already mentioned this to smartENERGY

**Comment by d0tcc** [comment]
Could it be that they changed it again and the price provided by the SmartEnergy API now does include the Tax (but no absolute surcharge)?
So the only way I get the price that they claim on their website is by adding 20% surcharge and 1.44ct absolute surcharge.

**Example for 2024-09-08T10:00:00+02:00:**

EPEX Spot price: 0.829ct
SmartEnergy API price: 0.995ct (0.829*1.2)
SmartEnergy Website price: 2,43ct (0.829*1.2+1.44)

**Comment by angeeinstein** [comment]
> > According to smartENERGY, the prices reported by the API already include 20% tax
> 
> That is wrong, even though they say it on their website. The provided price from smartENERGY is without tax. It's the same as on the EPEX Spot website. You have to add a surcharge of 1,2ct and then 20% tax. That gives you the 1,44ct (1,2×1,2) surcharge that you really pay to smartENERGY.

That is still true, just checked.

**Comment by xiaodi-dev** [comment]
1. SmartEnergy API provides the correct price with 20% VAT without the surcharge of 1.44 ct. Currently, the price is calculated (spot price + 1.44) * 1.2 which is incorrect. It should be spot price *1,2 + 1.44.
2. Is there a possibility of changing all prices from MWh to kWh?
3. Is possible to have all the prices (average, highest, lowest, median) with the same price structure as the net price with VAT and surcharge?

**Comment by suaveolent** [comment]
@xiaodi-dev 
1.) Thanks, I have fixed the calculation in `3.0.0-dev-2`. Surcharge needs to be adapted accordingly.
2.) See latest pre-release `3.0.0-dev-2`. It changes all prices to currency/kWh
3.) It is not yet planed. But seems like a reasonable addition. I might add support for it.

**Comment by daschmidt1994** [comment]
I have to set this with tax and 1,44cent for the right price.

![Image](https://github.com/user-attachments/assets/c228565b-d12b-488b-9fe4-a43f1b11af65)

**Comment by jojoob** [comment]
Something seems to be broken with net price calculation for the smartENERGY source.

The README says:

```
Percentage Surchage = 3%
Absolute Surcharge = 0.012 €/£/kWh
Tax = 19%

Net Price = ((Market Price * 1.03) + 0.012) * 1.19
```

But at least for the smartENERGY source the calculation is Net Price = (Market Price * Tax) + Absolute Surcharge. I haven't figured out how percentage surcharge fits into that formula. Seems #165 and specifically 701fedcd0a30471b71549033a6938da073705d31 introduced this weirdness. Don't know how it was before because I just installed the integration for the first time.

**Comment by suaveolent** [comment]
> Something seems to be broken with net price calculation for the smartENERGY source.
> 
> The README says:
> 
> ```
> Percentage Surchage = 3%
> Absolute Surcharge = 0.012 €/£/kWh
> Tax = 19%
> 
> Net Price = ((Market Price * 1.03) + 0.012) * 1.19
> ```
> 
> But at least for the smartENERGY source the calculation is Net Price = (Market Price * Tax) + Absolute Surcharge. I haven't figured out how percentage surcharge fits into that formula. Seems [#165](https://github.com/mampfes/ha_epex_spot/pull/165) and specifically [701fedc](https://github.com/mampfes/ha_epex_spot/commit/701fedcd0a30471b71549033a6938da073705d31) introduced this weirdness. Don't know how it was before because I just installed the integration for the first time.

Thanks, the readme was apparently never adapted. It is on the todo list to either adapt the README or revert the fix. I will keep you updated.

**Comment by jojoob** [comment]
My vote goes for reverting the "fix".

**Comment by wmtech-1** [comment]
> My vote goes for reverting the "fix".

All providers with the same basic data should be treated equally.
The problem is the wrong statement at Smartenergy's web site to include tax in their feed.
