### ISSUE TITLE
Wrong values - using smartenergy.at

### ISSUE THREAD

**Issue by hatl** [mampfes/ha_epex_spot#113]
Hi

Just installed the integration. Unfortunately, it seems to deliver incorrect values.
The net price of 23.70 ct seems to be wrong.
Or am I missing something?

![image](https://github.com/mampfes/ha_epex_spot/assets/70505/ccdd166d-199b-4ef0-bea7-8bf5d8fe7424)

![image](https://github.com/mampfes/ha_epex_spot/assets/70505/af7a7e6b-1d3a-41ad-bf6a-cba58bc4b9f1)

![image](https://github.com/mampfes/ha_epex_spot/assets/70505/c9e49ad4-1504-458f-a137-c7a47d28ebc2)

![image](https://github.com/mampfes/ha_epex_spot/assets/70505/8b554a9b-80e1-418d-83e3-b929edc632af)

**Comment by mampfes** [comment]
Did you configure tax and surcharges in the configuration dialog of the integration?

**Comment by hatl** [comment]
Thanks for the hint! I overlooked that config parameters somehow.

Maybe set the default values when configuring smartENERGY.at?

| Parameter                   | Value |
| :-------------------------- | :---- |
| Percentage Surcharge (%)    | 0     |
| Absolute Surcharge (ct/kWh) | 1.2   |
| Tax (%)                     | 20    |
