### ISSUE TITLE
SMARD no longer working

### ISSUE THREAD

**Issue by functionpointer** [mampfes/ha_epex_spot#118]
Since midnight (05-04-2024T00:00:00) SMARD is no longer working.
![image](https://github.com/mampfes/ha_epex_spot/assets/9073578/ff6393c9-dcaf-4e69-8fa8-e2d3e7f77efd)

Logs say this:
```
Apr 05 01:55:20 netberry hass[15360]: 2024-04-05 01:55:20.101 ERROR (MainThread) [custom_components.epex_spot.SourceShell] no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object a>
Apr 05 01:55:20 netberry hass[15360]: 2024-04-05 01:55:20.101 ERROR (MainThread) [custom_components.epex_spot.SourceShell] no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object a>
Apr 05 01:55:20 netberry hass[15360]: 2024-04-05 01:55:20.101 DEBUG (MainThread) [custom_components.epex_spot] Finished fetching epex_spot data in 0.000 seconds (success: True)
```

**Comment by Matze-aaa** [comment]
Same here.

**Comment by morph027** [comment]
Confirmed.

**Comment by morph027** [comment]
Debug output: https://password.morph027.de/#/send/z0XwxeP7TZmGmfzeB9mY3Q/C2-gEFgi_dRUi8OuLQFdug

**Comment by Adminius** [comment]
Same here.
But also Stromampel.de doen't work. The question if they using the same provider or not...
Also https://newtransparency.entsoe.eu/ has issues

**Comment by hnico21** [comment]
Same. Stopped working after updating Home Assistant.

**Comment by functionpointer** [comment]
It randomly started working again. Was it an outage of the API? Hard to say without more detailed logging

**Comment by morph027** [comment]
Jip, working again here too.

**Comment by mampfes** [comment]
This outage was caused by the unavailability of the SMARD API on the server side.
