### ISSUE TITLE
EPEX Spot Web Scraper (CH) not working anymore

### ISSUE THREAD

**Issue by ullibak** [mampfes/ha_epex_spot#132]
EPEX Spot Web Scraper to retrieve Swiss spot prices does not work anymore. Prices are not available.

I use version 2.3.5 and everything works fine if I choose Austra (AT) as country.

**Comment by PhillWalker** [comment]
Seeing the same problem here in the UK...

EPEX Spot Web Scraper (GB)
all data unavailable
