### ISSUE TITLE
EPEX Spot Web Scraper (AT) not working

### ISSUE THREAD

**Issue by AkshayRao27** [mampfes/ha_epex_spot#139]
The EPEX Spot Web Scraper (v2.3.7) doesn't seem to be working since today. The specific error is:

`Failed setup, will retry: 403, message='Forbidden', url=URL('https://www.epexspot.com/en/market-data?market_area=AT&trading_date=2024-06-28&delivery_date=2024-06-29&auction=MRC&modality=Auction&sub_modality=DayAhead&product=60&data_mode=table&ajax_form=1')`

![image](https://github.com/mampfes/ha_epex_spot/assets/44117116/7e5d4d6e-0a34-44b4-a75b-309f5ee3d2de)

Edit: Seems to be the same as #138

**Comment by mathieudz** [comment]
Same here (be)

**Comment by kverbeke** [comment]
Same here. Problem started yesterday after restarting HASS.

**Comment by bjruberg** [comment]
Same here for DE

**Comment by networkerict** [comment]
Same here for NL.

**Comment by WimGo** [comment]
I have the same error, for BE.
If you look at the URL, you see the date of yesterday. I could assume that the data of yesterday are not available anymore, and the error could come from there.
But why does the code requests yesterday's data? Should be today's data in the request, no?

**Comment by AkshayRao27** [comment]
Opening that URL in the browser doesn't work even when the dates are correct. It only works once `&ajax_form=1` is removed from the URL.

**Comment by WimGo** [comment]
> I have the same error, for BE. If you look at the URL, you see the date of yesterday. I could assume that the data of yesterday are not available anymore, and the error could come from there. But why does the code requests yesterday's data? Should be today's data in the request, no?

The solution in https://github.com/mampfes/ha_epex_spot/issues/138 , same issue, worked for me.

**Comment by mampfes** [comment]
Release 2.3.8: https://github.com/mampfes/ha_epex_spot/releases/tag/2.3.8
