### ISSUE TITLE
Feature request: Sensors for cheapest hour, most expensive hour, median and so on

### ISSUE THREAD

**Issue by riesi77** [mampfes/ha_epex_spot#14]
Hi,

thanks for this integration. In order to add automations it would be great to have sensors that show the most expensive hour(s), the cheapest hour(s) and also the average / median price of the day.
There is already a solution in the following discussion - but it would be great having that included in your integration.

https://community.home-assistant.io/t/problem-in-building-a-json-list-of-data/171736/32

Thanks.

**Comment by mampfes** [comment]
Interesting request! Before I start implementing, I need some more information:

Do you want to have a sensor with the start time of the cheapest hour as value? For the current day, or from the beginning of the current day until the end of the available data, or from now till the end of the available data?

What do you think of this proposal: A sensor which provides the following value: The number of cheaper hours during the current day. So, if you are currently within the cheapest hour, it would return 0. If you are within the most expensive hour it would return 23. But always only for current day. So, from a automation point of view you just have to compare the value against your desired range:

- If you want to have an indication for the 2 cheapest hours of the day, you want compare it as follows: `value < 2`
- If you want to have an indication for the 5 most expensive hours, use `value >= 19`

In addition, I would provide the average and median price of the current day.

**Comment by riesi77** [comment]
Thanks for the fast reply. 
Regarding your question: current day or the whole period of available data. There is this discussion in the thread I linked already. I am a fan of taking 24h - so always taking a day from 0:00 to 23:59. This ensures that I really have - let's say a heating rod - running for x hours.  Also your (great) idea of ranking works better when having the fixed timeframe and if it does not change in the middle of the day.
Regarding the proposal: I really like the idea. Just 1 concern: It should be ensured that this really works as a trigger in homematic automations to turn on and turn off devices. I'n no expert in homematic - but I'm not sure how I would configure the trigger. Until now, I have even 2 sensors per hour:
cheapest_hour_starts_timestamp
cheapest_hour_ends_timestamp
as well as
mostexpensive_hour_starts_timestamp
mostexpensive_hour_ends_timestamp

If sth. similar would be possible with your approach, it would be more flexible.

Thanks.
