### ISSUE TITLE
SmartEnergy broken

### ISSUE THREAD

**Issue by Zappelphilipp** [mampfes/ha_epex_spot#143]
Hi everyone,

unfortunately i have not yet been able to pinpoint the exact cause, but i have not been getting any data in homeassistant for the smartenergy source since july 19th 06:00. this is the error i am getting:

```
Logger: custom_components.epex_spot_sensor.binary_sensor
Source: custom_components/epex_spot_sensor/binary_sensor.py:387
integration: EPEX Spot Sensor ([documentation](https://github.com/mampfes/ha_epex_spot_sensor), [issues](https://github.com/mampfes/ha_epex_spot_sensor/issues))
First occurred: July 19, 2024 at 8:00:46 AM (1450 occurrences)
Last logged: 8:05:00 AM
Invalid price sensor "sensor.epex_spot_data_net_price" selected for EPEX Spot Sensor "EPEX cheapest price": "'data' missing in sensor attributes"
```

tried awattar for testing purposes and it worked right away. Does anybode else has the same problem?

**Comment by jeff1975** [comment]
same problem since Friday

**Comment by olvrlrnz** [comment]
Their [API](https://apis.smartenergy.at/market/v1/price) doesn't return any data, so I guess there's not much the addon can do

**Comment by Zappelphilipp** [comment]
seems like the API from smartenergy is actual broken because https://apis.smartenergy.at/market/v1/price does not reply anything

**Comment by Tomschin** [comment]
Maybe it is "CrowdStrike" related?

**Comment by soonup** [comment]
> seems like the API from smartenergy is actual broken because https://apis.smartenergy.at/market/v1/price does not reply anything
> 
> EDIT: @olvrlrnz mentioned already at the same time

the API seems to be back online. everything working as usual in home assistant :-)

**Comment by jeff1975** [comment]
Thanks for your information! Everything OK

**Comment by killtux** [comment]
is it possible that its down again?

i dont have any values since 5th of october.

**Comment by Tomschin** [comment]
Yes it is broken again. 
There where also no Charts on the web page.
Today there a Charts again on the web page. So we can hope that it will work tomorrow.

**Comment by soonup** [comment]
it's up again for me :-)

**Comment by Tomschin** [comment]
And now something (not totally) different: The new data for the next day should be available at 17:00. But it only appears on the webpage not in the interface. There it is delayed. Does someone have the same "expirience"?
