### ISSUE TITLE
Loading new data not working / working with delay

### ISSUE THREAD

**Issue by sas413** [mampfes/ha_epex_spot#162]
Hello,

I have configured it with smartenergy.at. It seems to be working, but the new values are not fetched at 5pm.
Is there any way to configure this?
Today the values haven't been there after 7pm. After a reload of the integration, the new values where fetched.
Have I missed some config or is this a bug?
Thank you

**Comment by sas413** [comment]
I found out, that it seems like a problem on smartenergy side. The API does not deliver values for the next day at 5pm. Yesterday, the values for the next day where available in the API after 8pm.

**Comment by suaveolent** [comment]
Thanks for letting us know. Might add an info to the readme.

**Comment by sas413** [comment]
I wrote an email to smartengery to fix this. On their website the new values for the next day are available on 5pm. So I would expect them in the API to.
