### ISSUE TITLE
Netherlands net price incorrect value

### ISSUE THREAD

**Issue by Little709** [mampfes/ha_epex_spot#166]
![image](https://github.com/user-attachments/assets/15bea021-189f-4af8-846f-9a3b681339e7)

With the new update, the net price for the netherlands seems a little off. I'd expect it to be around ~10 cents higher than the bare prices. ;)

**Comment by Little709** [comment]
It was indeed in the user options! 

what i noticed is that i couldn't input 0.0. i had to put 0.0258 in another text field and then copy it. Do you have control about the allowed number that can be entered into the textbox?

**Comment by suaveolent** [comment]
Thanks for letting me know. 


Unfortunately this seems to be an issue with home assistant itself. 
Best we create an issue there.
