### ISSUE TITLE
2.3.9 - price calculation

### ISSUE THREAD

**Issue by Skol6** [mampfes/ha_epex_spot#175]
Hi,

does the release 2.3.9 also contain the changes of 3.0.0-dev-2?
For the energy panel "change to price per kWh instead of ct or MWh" is necessary.

Regards,
skol

**Comment by suaveolent** [comment]
No 2.3.9 is only a fix for the EPEX Spot changes. 

Only versions 3.0.0 and up will have the price per kWh changes.

**Comment by Skol6** [comment]
When will there be a combined Release?

Am 23. November 2024 10:40:47 schrieb suaveolent ***@***.***>:

**Comment by suaveolent** [comment]
The fix is also included in the 3.0.0-dev4 release so you can already upgrade to the pre-release.

**Comment by Skol6** [comment]
Thanks

Am 23. November 2024 11:03:15 schrieb suaveolent ***@***.***>:
