### ISSUE TITLE
Show EPEX Spot Data Net Price in "EUR/KWh"

### ISSUE THREAD

**Issue by pgerstbach** [mampfes/ha_epex_spot#177]
I wonder why EPEX Spot Data Net Price has the unit "ct/KWh" and not "EUR/KWh".

The HA Energy dashboard allows use an entity with current price, but it requires "EUR/KWh". So I created a derived sensor via configuration.yaml that just takes the "EPEX Spot Data Net Price" * 100. 

I am really new to HA, but I wonder if there is a simpler way that could be integrated into this addon?

**Comment by suaveolent** [comment]
You can upgrade to latest pre-release. This addresses exactly this issue :)
