### ISSUE TITLE
Sensor data not available

### ISSUE THREAD

**Issue by biberyeti** [mampfes/ha_epex_spot#20]
HI, thanks for dthis nice HASS integration of awattar. After installing it I do not get any data from the sensors. I am sure it is a very stupid mistake as this is my first HACS integration
Cheers

**Comment by mampfes** [comment]
Which version are you using? I released a new version 1.1.1 yesterday which fixes a different issue, but maybe I did a mistake here.
Are you using `at` or `de`?
Do you see sensors without values, or no sensors at all?

**Comment by biberyeti** [comment]
Hi,

It was the latest one. So yes or is the 1.1.1 from Yesterday evening
And I am using the at

Cheers,
Andreas

Steffen Zimmermann ***@***.***> schrieb am Mo., 17. Apr.
2023, 07:15:

**Comment by patsch9** [comment]
same here, no data available after configure the integration for DE (Awattar and EPEX) 
![image](https://user-images.githubusercontent.com/47031716/232467737-2d302b39-ceee-4052-aec1-e4f42fbdafe6.png)

**Comment by mampfes** [comment]
There seems to be a problem with version 1.1.1 with I don't on my development machine. Please go back to version 1.1.0.
