### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by gigatexel** [mampfes/ha_epex_spot#26]
Today around 09:00 CET the integration stopped working (all sensors `Unavailable`).
Downgrade to 1.1.2 fixes this issue.

Is there any kind of debugging in this integration?
I added `custom_components.epex_spot: debug` to the logger, but there is no output.

**Comment by mampfes** [comment]
Are you using the EPEX Spot source? The service is currently offline:
![image](https://github.com/mampfes/ha_epex_spot/assets/375950/d181e989-85fe-49e6-8c14-4b35f50c3db5)
Awattar is still working. So this is not an issue of the integration, but on the service provider.

**Comment by gigatexel** [comment]
Ok, this will be the cause :-)
