### ISSUE TITLE
Net-Price Sensor is wrong

### ISSUE THREAD

**Issue by outrun0506** [mampfes/ha_epex_spot#27]
Hi,

I had look today at the new Net-Price Sensor.

The Epex Spot Price was € 9,37/MWh on my test

If I set Supercharge and Tax to Zero, the Net Price sensor Reports 1ct/KWh - i assume it should be 0,937ct/KWh. Or do I understand that wrong?

Br and have a nice Weekend

**Comment by mampfes** [comment]
Yes, if you set `Percentage Surcharge` and `Absolute Surcharge` and `Tax` to 0, you should get the market price in ct/kWh. Please note that by default, the net price sensor shows a rounded value with 2 decimal places - but this can be configured in the UI. Internally the full resolution is available.
On my machine, this works as expected.

**Comment by outrun0506** [comment]
I'll keep an eye on it and will update here with the new results. Currently it shows correctly, but the Spot Price is € 160/MWh so there is currently no rounding. Probably it was the case, because the price was so low...

**Comment by outrun0506** [comment]
Hi,
i did monitor this for serveral hours. So far it looks good. Don't know why i had a difference here yesterday. So i going an close the issue.

Thanks for your Support!
