### ISSUE TITLE
Rank and Qantile not numbers?

### ISSUE THREAD

**Issue by ProfDrYoMan** [mampfes/ha_epex_spot#30]
Hi,

both don't show as numbers and therefor not well in the graphs. Intended?

![image](https://github.com/mampfes/ha_epex_spot/assets/510353/8167d748-f542-46c1-a5e5-a6da6e6e77a0)

![image](https://github.com/mampfes/ha_epex_spot/assets/510353/abe05687-b930-4594-9b3c-431bd8dfe8a9)

**Comment by mampfes** [comment]
Hi, thanks for the info. No - this is not intended. I assume the reason for this is that I don't set a unit of measure for them. Will check...

**Comment by ProfDrYoMan** [comment]
You are right.

![image](https://github.com/mampfes/ha_epex_spot/assets/510353/8c7738ec-402a-4915-b475-04951a6c7806)

In customize.yaml:
```sensor.epex_spot_de_quantile:
  unit_of_measurement: '#'
sensor.epex_spot_de_rank:
  unit_of_measurement: '#'
```

For quantile showing in percent and giving values 0 .. 100 % might be a better choice?
