### ISSUE TITLE
Repository nicht gefunden

### ISSUE THREAD

**Issue by muxodo** [mampfes/ha_epex_spot#36]
Beim Versuch die Integration meiner HA Installation hinzuzufügen kommt die Meldung:
Repository mampfes/ha_epex_spot not found

**Comment by mampfes** [comment]
Which installation alternative did you use? HACS or manual?
Please describe your steps.

**Comment by muxodo** [comment]
I tried it over HACS. Searched for Epex. Then clicked on the button "Install EPEX Spot integration via HACS. Then there is a warning, that the link redirects to a custom integration. After open that link then the message Repository not found showed up

**Comment by mampfes** [comment]
Hm, strange. Currently I can't test this out by myself, therefore I can only give you some hints:

Do you mean the button in the description of the integration?  If yes, you can try to add the integration from the menu in HACS directly.

**Comment by mampfes** [comment]
any update on this?

**Comment by muxodo** [comment]
Tried it again and now it was working. No Idea what happened. Thanks for this add-on!
