### ISSUE TITLE
unit or calculation for net price wrong

### ISSUE THREAD

**Issue by aSauerwein** [mampfes/ha_epex_spot#47]
Hi, 

i just noticed that either the unit or the calculation for net price is wrong by factor 10. 
<img width="336" alt="image" src="https://github.com/mampfes/ha_epex_spot/assets/5446813/c7da9564-6391-4fcd-832b-93817e06c91d">
as an example:
current price: 10.46EUR/MWh == 1046 ct/MWh == 1,046 ct/kWh
+ absolute surcharge of 1.2 and 20% tax = 2,69ct/kWh == 26,952 EUR/MWh

so either the unit of the sensor should be changed to ct/kWh or the the price has to be multiplied by 10. 

I think ct/kWh has been done on purpose here:
https://github.com/mampfes/ha_epex_spot/blob/5bdf4228b60068c1f42272ee4decbb7526b5dcac/custom_components/epex_spot/SourceShell.py#L128

so it would be the easiest to just change the unit here:
https://github.com/mampfes/ha_epex_spot/blob/5bdf4228b60068c1f42272ee4decbb7526b5dcac/custom_components/epex_spot/sensor.py#L95

**Comment by mampfes** [comment]
Thanks! This is a copy/paste error from the big refactoring.

**Comment by aSauerwein** [comment]
thank you for the quick fix. looking good now!
<img width="307" alt="image" src="https://github.com/mampfes/ha_epex_spot/assets/5446813/adf3353e-caa7-496c-86b9-8ed56c92fb01">
