### ISSUE TITLE
get lowest price interval reports wrong data

### ISSUE THREAD

**Issue by derbadewaschl** [mampfes/ha_epex_spot#49]
Hi,

I just updated to 2.0.0. When I run the "Get lowest price interval" service from the Developer/Services menu with a duration of 2h, it will give me following answer:

> start: "2023-10-09T01:00:00+00:00"
end: "2023-10-09T03:00:00+00:00"
price_eur_per_mwh: 152.4
price_ct_per_kwh: 15.24
net_price_ct_per_kwh: 22.081919999999997

However, when you look at the attached raw data, the cheapest 2h interval is 2:00 - 4:00, not 1:00-3:00. Also, the price should be 12.114, not 15,24ct/kWh.

I am using ha 2023.9.2.

[epex_spot_data_net_price.txt](https://github.com/mampfes/ha_epex_spot/files/12841333/epex_spot_data_net_price.txt)

Regards

derbadewaschl

**Comment by mr-p666** [comment]
Hej,
this is because the service menu output does not show your local time.
Try it out. ;-)

**Comment by derbadewaschl** [comment]
you're right. it works fine from the template. thanks.
