### ISSUE TITLE
Show prices as €/kwh

### ISSUE THREAD

**Issue by arnold-maderthaner** [mampfes/ha_epex_spot#5]
hi !

would it be possible to show also the prices per kwh ?
I'm currently using the awattar configuration.

**Comment by zoesn89** [comment]
Hey @arnold-maderthaner,

you could use a template and divide the €/MWh value by 10, then you have ct/kWh ;)

**Comment by mampfes** [comment]
I agree. The short term solution is to add a template sensor. I added a new section **FAQ** with an example to README.md.

The best long-term solution in my mind would be to add EUR/MWh and ct/kWh to the unit conversion system of Home Assistant.

**Comment by gregstr** [comment]
I do understand the option to work with template sensors to get ct/kWh values. But I'm also working with the attribute values to calculate upcoming low prices. Any idea how to get attribute values converted easily. That is the main reason why I'm still using this fork although it's lacking some of the new sensors added recently: https://github.com/TheBrain8791/ha_awattar

**Comment by mampfes** [comment]
All prices are also available as ct/kWh in dedicated attributes since version 1.1.0. But I just realized that I didn't removed the outdated template example. Do you need more?

**Comment by gregstr** [comment]
Thanks for pointing that out! That's great.
Only challange remining: how to add e.g. tax and other price addons to all the values. Did anybody already come up with a template sensor with attribute templates?

**Comment by mampfes** [comment]
Please check release 1.2.0: I added a net price sensor in ct/kWh.

**Comment by aichingerk** [comment]
Tested the new sensor and it works great: 
![image](https://github.com/mampfes/ha_epex_spot/assets/82718567/a86945f3-ddc1-41b6-ba85-da2e853daf60)
This are fiktiv numbers, because i didn't receive a bill until yet from awatar.
Set following attribute:
Tax: 20 Austria
Surcharge 5%
absolut surcharge 5ct/kW
