### ISSUE TITLE
Error in service example?

### ISSUE THREAD

**Issue by gigatexel** [mampfes/ha_epex_spot#51]
Could it be that there is an error in the new example for calling the service?
VS signals an error and the template renders Unknown

![image](https://github.com/mampfes/ha_epex_spot/assets/65073191/8b43fa2f-8dba-412d-b4aa-fed6384aa985)

**Comment by mampfes** [comment]
Which home assistant version are you using?

**Comment by nin9s** [comment]
Having the same issue and using the latest version available

**Comment by mampfes** [comment]
It works on my machine if I put it into a yaml file (I didn't check the GUI). Maybe the VS syntax highlighter doesn't support this quite new feature yet.
Regarding the unknown state: In your example, the state will be only updated once per day, at 00:00.

**Comment by nin9s** [comment]
it does not make a difference, I adjusted the trigger time with no success.

**Comment by mampfes** [comment]
@nin9s Please share your configuration.

**Comment by nin9s** [comment]
`template:
  - trigger:
      - platform: time
        at: 15:02
    action:
      - service: epex_spot.get_lowest_price_interval
        data:
          earliest_start: "09:00:00"
          latest_end: "18:00:00"
          duration:
            hours: 1
        response_variable: resp
    sensor:
      - name: epex_lowest_intervall
        device_class: timestamp
        state: "{{ resp.start is defined and resp.start }}"
`

**Comment by mr-p666** [comment]
Again... I'm just a n00b at HASS.
But don't you always need quotation marks around the time so that the colon is not misinterpreted?
eg "15:02:00"

**Comment by aichingerk** [comment]
hi, please look also into the topic: https://github.com/mampfes/ha_epex_spot/discussions/50

**Comment by mampfes** [comment]
Any updates?

**Comment by nin9s** [comment]
Fixed for me
