### ISSUE TITLE
show a price chart for the next 24 h

### ISSUE THREAD

**Issue by arnold-maderthaner** [mampfes/ha_epex_spot#6]
Hi !

Would it be possible somehow to create a graph based on the available prices for the next 24h that could be shown then in HA ?

**Comment by thomasdelaet** [comment]
I did this with apexcharts card which is available on HACS

`  - type: custom:apexcharts-card
    header:
      show: false
      title: Electricity Price Dynamic
      colorize_states: true
    graph_span: 48h
    span:
      start: day
    now:
      show: true
      color: var(--primary-color)
      label: Now
    series:
      - entity: sensor.epex_spot_be_price
        opacity: 0.9
        name: Electricity Price
        stroke_width: 6
        type: line
        curve: smooth
        color: var(--primary-color)
        show:
          in_header: true
          legend_value: true
          name_in_header: true
        extend_to: end
        data_generator: |
          return entity.attributes.data.map((entry, index) => {
            return [new Date(entry.start_time).getTime(), entry.price_eur_per_mwh];
          });
`

**Comment by functionpointer** [comment]
Thanks @thomasdelaet, very nice graph.

Here is the graph card with proper formatting:

```type: custom:apexcharts-card
header:
  show: false
  title: Electricity Price Dynamic
  colorize_states: true
graph_span: 48h
span:
  start: day
now:
  show: true
  color: var(--primary-color)
  label: Now
series:
  - entity: sensor.epex_spot_be_price
    opacity: 0.9
    name: Electricity Price
    stroke_width: 6
    type: line
    curve: smooth
    color: var(--primary-color)
    show:
      in_header: true
      legend_value: true
      name_in_header: true
    extend_to: end
    data_generator: |
      return entity.attributes.data.map((entry, index) => { return [new Date(entry.start_time).getTime(), entry.price_eur_per_mwh]; });
```

Pro tip: Use triple backtics for multi-line code ```` ```like this``` ````. Use the preview tab to check if it is working.

**Comment by mampfes** [comment]
Wow, this is really cool! I added your example to the docu. Thank you very much.
