### ISSUE TITLE
get_lowest_price_interval result: average or sum?

### ISSUE THREAD

**Issue by s4andst0rm** [mampfes/ha_epex_spot#60]
Hi,

the documentation for the **epex_spot.get_lowest_price_interval** service  says
`
 The response contains the calculated start and end-time and the AVERAGE price per MWh/KWh for the whole duration.
`

However, when I call the service with a duration of _2 hours_, the price_eur_per_mwh and price_ct_per_kwh seems to be the **sum** of the 2 resulting hours - not the **average** value:

```
service: epex_spot.get_lowest_price_interval
data:
  earliest_start: '01:00:00'
  earliest_start_post: 1
  latest_end: '07:00:00'
  latest_end_post: 1
  duration:
    hours: 2 
```

Result:
```
start: "2023-10-30T00:00:00+00:00"
end: "2023-10-30T02:00:00+00:00"
price_eur_per_mwh: 16.75
price_ct_per_kwh: 1.675
net_price_ct_per_kwh: 8.586
```

When querying it for the duration of _1 hour_, the result is:
```
start: "2023-10-30T01:00:00+00:00"
end: "2023-10-30T02:00:00+00:00"
price_eur_per_mwh: 8.36
price_ct_per_kwh: 0.836
net_price_ct_per_kwh: 7.5792
```

The epex_spot_net_price for the time in question is:
```
- start_time: '2023-10-30T00:00:00+00:00'
  end_time: '2023-10-30T01:00:00+00:00'
  price_ct_per_kwh: 7.582800000000001
- start_time: '2023-10-30T01:00:00+00:00'
  end_time: '2023-10-30T02:00:00+00:00'
  price_ct_per_kwh: 7.5792
```

The epex_spot_price for the time in question is:
```
- start_time: '2023-10-30T00:00:00+00:00'
  end_time: '2023-10-30T01:00:00+00:00'
  price_eur_per_mwh: 8.39
  price_ct_per_kwh: 0.8390000000000001
- start_time: '2023-10-30T01:00:00+00:00'
  end_time: '2023-10-30T02:00:00+00:00'
  price_eur_per_mwh: 8.36
  price_ct_per_kwh: 0.836
```

So the _price_eur_per_mwh_ seems to be 8.39+8.36=16.75 which is the **sum**, not the **average**.
Same for _price_ct_per_kwh_: 0.839+0.836=1.675.

_net_price_ct_per_kwh_ for 1 hour returns 7.5792, which matches with the _price_ct_per_kwh_ from  epex_spot_net_price
_net_price_ct_per_kwh_ for 2 hours returns 8.586, which is neither sum nor average of 7.5828 and 7.5792 .. so **how is this calculated**?

So is the behavior returning the sum the expected one, and the documentation does not match, or vice versa - or is the implementation going to change (soon)? ... Or do I misunderstand something entirely?

I need the average price in the resulting time period for my automation, so I have to divide by the amount of hours to get the average price - but if the implementation will change in the future, I have to know - because I have to adjust my calculations then.

BTW .. I am using the release 2.1.0

Thanks.

**Comment by mampfes** [comment]
Yes, you are right. The price was calculated for the whole interval instead of 1h. I added a fix. Please try out the main branch.

**Comment by s4andst0rm** [comment]
Thank you, now it works as expected and returns the average price for the interval.
_net_price_ct_per_kwh_ also returns the expected average net price now.
