### ISSUE TITLE
Wrong time, maybe timezone problem?

### ISSUE THREAD

**Issue by pos-ei-don** [mampfes/ha_epex_spot#73]
Here I compare the aWattar Webpage with the Data within HA and the json.

shouldn't Homeassistant use the current timezone information to display the correct values?
The Webpage from aWattar seems to do so!

![grafik](https://github.com/mampfes/ha_epex_spot/assets/1822533/7d4f56fd-630a-40e9-988d-cb2559eb314e)

**Comment by mampfes** [comment]
The raw times in the developer windows are shown in UTC (indicated by the timezone offset Z or +00:00), not in local time (probably CET).
HA takes care about the conversion when it displays the timestamps!
