### ISSUE TITLE
Feature request: Rank calculation for future hours

### ISSUE THREAD

**Issue by airman84** [mampfes/ha_epex_spot#74]
Hello,

do you think it would be possible to have the rank for future hours added as attribute to the rank sensor, similar as it is for the net price? Right now the rank is just visible for the past hours. So it would be possible to see, in which hours a device will be turned on/off, when triggering that by an automation using the rank as condition. 

Thank you

**Comment by mampfes** [comment]
Good idea. Let me check.

**Comment by mihmihmih1988** [comment]
+1

**Comment by hlinden** [comment]
+1

**Comment by hlinden** [comment]
![Bildschirmfoto vom 2024-01-05 00-55-58](https://github.com/mampfes/ha_epex_spot/assets/4718458/639da128-12e6-4f13-8c6e-324c9bcbe977)

Very neat, now I have a graph fro the entire day that shows the planned runtimes of the heat pump. Thank you!
