### ISSUE TITLE
Net Price Attributes for next day lost

### ISSUE THREAD

**Issue by airman84** [mampfes/ha_epex_spot#75]
Hello,

i came already often about this issue: 
Prices for the next day are usually loaded in the early afternoon, displayed and working as expected. As well my template sensor made a service call for the cheapest hour of the next day and the returned result for the next day fine. Right now, there is not any Net Price Date for tomorrow anymore, it simply ends at midnight. Reloading the integration resolves the issue immediately.

Any idea whats going on here? 
Thank you!

**Comment by airman84** [comment]
For me it happened again yesterday and right now with source EPEX Spot Web Scraper (AT). Unfortunately there are not any hints in the log, even when enabling debug logging.

**Comment by mampfes** [comment]
Any update on this? Do you also see this issue if you use another source, like SMARD or Awattar?

**Comment by airman84** [comment]
It's still happening to me quite often. I switched now to the smartenergy source and hope this will solve it.
Thank you!
