### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by pabe40** [mampfes/ha_epex_spot#89]
EPEX spot integration failed to setup: Cannot connect to host [www.epexspot.com:443](http://www.epexspot.com:443/) '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

**Comment by pabe40** [comment]
Issue linked to core update to core-2024.1.2 ? 
Or linked to Epex Spot update : I have version 2.3.0 ?

**Comment by tricksel** [comment]
Same here.

**Comment by mampfes** [comment]
Fixed in release 2.3.1

**Comment by pabe40** [comment]
Fort my info : Which CA store is used by epex spot? Is it relying on the core of HA? Which location on filesysteem?

**Comment by mampfes** [comment]
Epex spot doesn't use an own ca store. It relies on what Python/HA provides.
