### ISSUE TITLE
How to configure??

### ISSUE THREAD

**Issue by dominikfe** [mampfes/ha_epex_spot#9]
Hi!
I cant find any information how to configure your addon. I have installed it manually and it loads during HA startup but there is no sensor being created. Can you please add further information to your documentation?
Thank you!
ps. thank you for the effort to create this addon!

**Comment by mampfes** [comment]
Did you follow step 3?
![image](https://user-images.githubusercontent.com/375950/214131051-1d473406-3b1d-4429-8ebe-250c23783b8e.png)

Manual procedure: Settings --> Devices & Services --> + Add Integration --> Select Epex Spot

**Comment by dominikfe** [comment]
Silly me! Overlooked "add integration" / confused it with HACS installation.
This can be closed/deleted.
